# Prometheus Configuration File (prometheus.yml):
#
global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'eks-cluster'
    scrape_interval: 15s
    static_configs:
      - targets: [':']
        labels:
          service: 'eks-cluster'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'container_cpu_usage_seconds_total'  # Replace with the metric
name you want to relabel
        target_label: 'cpu_usage_seconds'